### ISSUE TITLE
RHEL 9.1 also Rocky 9.1 does not build

### ISSUE THREAD

**Issue by mikeyjoon** [SCST-project/scst#101]
Compilation is broken for OS  RHEL 9.1 kernel 5.14.0-162.6.1.el9_1.x86_64:
---------------------------------------------------------------------------------
[root@scspa2671671002 ontap-mediator-1.6.0]# uname -a
Linux scspa2671671002.rtp.openenglab.netapp.com 5.14.0-162.6.1.el9_1.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Sep 30 07:36:03 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
[root@scspa2671671002 ontap-mediator-1.6.0]#

[root@scspa2671671002 ontap-mediator-1.6.0]# cat /etc/redhat-release
Red Hat Enterprise Linux release 9.1 (Plow)
[root@scspa2671671002 ontap-mediator-1.6.0]# cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="9.1 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.1"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.1 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/9/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.1
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1"
[root@scspa2671671002 ontap-mediator-1.6.0]#

Compilation error below:
---------------------------
[2022-11-28 18:42:05] In file included from /tmp/ontap_mediator.UFnM45/ontap-mediator-1.6.0/ontap-mediator-1.6.0/dist/scst/scst-3.7.0-pre/scst/src/../include/scst.h:54,
[2022-11-28 18:42:05]                  from /tmp/ontap_mediator.UFnM45/ontap-mediator-1.6.0/ontap-mediator-1.6.0/dist/scst/scst-3.7.0-pre/scst/src/scst_copy_mgr.c:17:
[2022-11-28 18:42:05] ./include/scsi/scsi_cmnd.h:179:6: note: previous declaration of 'scsi_done' with type 'void(struct scsi_cmnd *)'
[2022-11-28 18:42:05]   179 | void scsi_done(struct scsi_cmnd *cmd);
[2022-11-28 18:42:05]       |      ^~~~~~~~~

**Comment by lnocturno** [comment]
Hi,

Thank you for the report!

Fix candidate was merged to the master branch.

Thanks,
Gleb

**Comment by mikeyjoon** [comment]
Hi Gleb,

I verified the fix in the latest HOL (scst-master). Thanks so much for such a quick turnaround. I do, greatly, appreciate it.


Best Regards,
Mike
