### ISSUE TITLE
nothing provides /bin/killall

### ISSUE THREAD

**Issue by Tualua** [SCST-project/scst#152]
Hello!

scstadmin RPM cannot be installed with dnf with following error

```nothing provides /bin/killall needed by scstadmin-1.0.0-1.x86_64```

However, you can install it with rpm.

Is it possible to fix this?

**Comment by Tualua** [comment]
OS: Oracle Linux 9.1

psmisc is installed

`# which killall
/bin/killall`

**Comment by Tualua** [comment]
OS: Oracle Linux 9.1

psmisc is installed

`# which killall
/bin/killall`

**Comment by Tualua** [comment]
OS: Oracle Linux 9.1

psmisc is installed

`# which killall
/bin/killall`

**Comment by lnocturno** [comment]
Hi,

Thank you for the report!

I have created PR https://github.com/SCST-project/scst/pull/154
Could you retest the bug with this patch?

Thanks,
Gleb

**Comment by Tualua** [comment]
> Hi,
> 
> Thank you for the report!
> 
> I have created PR #154 Could you retest the bug with this patch?
> 
> Thanks, Gleb

Hello! I will try in a couple of days, thank you!
RIght now I used this workaround 

    - name: Fix spec file for scstadmin
      ansible.builtin.lineinfile:
        path: /root/scst-3.7/scstadmin/scstadmin.spec.in
        regexp: "^Requires"
        line: "Requires:       psmisc coreutils"
