### ISSUE TITLE
Crash at qla_mapq_init_qp_cpu_map()

### ISSUE THREAD

**Issue by hcbwiz** [SCST-project/scst#156]
Hi, 
   This commit:

    commit a1ff8c3ae93d793e5f2b79477b33e1bea9b2660a
    Author: Gleb Chesnokov <gleb.chesnokov@scst.dev>
    Date:   Sun Mar 12 16:25:55 2023 +0300

    qla2x00t-32gbit: Select qpair depending on which CPU post_cmd() gets called

    In current I/O path, Tx and Rx may not be processed on same CPU. This may
    lead to thrashing and optimum performance may not be achieved.

    Pick qpair such that Tx and Rx are processed on same CPU.

   **pci_irq_get_affinity()** gets NULL value in **qla_mapq_init_qp_cpu_map()** if it turns on target mode:
   
In qla24xx_enable_msix():
```
	if (USER_CTRL_IRQ(ha) || !ha->mqiobase) {
		/* user wants to control IRQ setting for target mode */
		ret = pci_alloc_irq_vectors(ha->pdev, min_vecs,
		    min((u16)ha->msix_count, (u16)(num_online_cpus() + min_vecs)),
		    PCI_IRQ_MSIX);
	} else
		ret = pci_alloc_irq_vectors_affinity(ha->pdev, min_vecs,
		    min((u16)ha->msix_count, (u16)(num_online_cpus() + min_vecs)),
		    PCI_IRQ_MSIX | PCI_IRQ_AFFINITY,
		    &desc);
```

This patch try to handle it:
```
diff --git a/qla2x00t-32gbit/qla_inline.h b/qla2x00t-32gbit/qla_inline.h
index c3f1b3b7..6b2716e5 100644
--- a/qla2x00t-32gbit/qla_inline.h
+++ b/qla2x00t-32gbit/qla_inline.h
@@ -550,11 +550,19 @@ qla_mapq_init_qp_cpu_map(struct qla_hw_data *ha,
        if (!ha->qp_cpu_map)
                return;
        mask = pci_irq_get_affinity(ha->pdev, msix->vector_base0);
+       if (!mask) {
+               goto fallback;
+       }
        qpair->cpuid = cpumask_first(mask);
        for_each_cpu(cpu, mask) {
                ha->qp_cpu_map[cpu] = qpair;
        }
        msix->cpuid = qpair->cpuid;
+
+fallback:
+       for_each_possible_cpu(cpu) {
+               ha->qp_cpu_map[cpu] = NULL;
+       }
 #endif
 }
```

**Comment by lnocturno** [comment]
Hi,

Thank you for the report!

I'll try to find time to take a look at the problem next week.

Thanks,
Gleb

**Comment by hcbwiz** [comment]
Hi,

I have no equipment to retest it.
However, the patch is okay to me
