### ISSUE TITLE
scst 3.7 somthing funtion  build error ，I have some ideas

### ISSUE THREAD

**Issue by luyuantaolll** [SCST-project/scst#190]
I encountered the same problem as "scst run failures to build # 113" ,

![1694143169753](https://github.com/SCST-project/scst/assets/52696697/bc894cc0-6909-4699-96ff-6ef862b575ce)

This seems to be caused by conflicts between some functions of the scst and kernel functions。
I tried renaming the conflicting function, and the result was successful compilation without any errors during installation
This is my modification
 [0001-build-fix.patch](https://github.com/SCST-project/scst/files/12555185/0001-build-fix.patch)

I think avoiding conflicts with kernel functions is a good approach, even if the functions of the reconstructed kernel functions are roughly the same

**Comment by goclm** [comment]
Excuse me, how to use this package? I also encountered a failure in building scst3.7.

**Comment by luyuantaolll** [comment]
> I encountered the same problem as "scst run failures to build # 113" ,
> 
> ![1694143169753](https://user-images.githubusercontent.com/52696697/266493185-bc894cc0-6909-4699-96ff-6ef862b575ce.png)
> 
> This seems to be caused by conflicts between some functions of the scst and kernel functions。 I tried renaming the conflicting function, and the result was successful compilation without any errors during installation This is my modification [0001-build-fix.patch](https://github.com/SCST-project/scst/files/12555185/0001-build-fix.patch)
> 
> I think avoiding conflicts with kernel functions is a good approach, even if the functions of the reconstructed kernel functions are roughly the same
