### ISSUE TITLE
Unable to build iscsi-scst on Rocky linux 9.3 with OFED drives

### ISSUE THREAD

**Issue by msdosx** [SCST-project/scst#202]
Hello,
I have a server with Rocky Linux 9.3 and mellanox ofed 23.10 installed drivers.
with this configuration I can't build the iscsi driver
Could you take a look?
Thank you.
  Building against MOFED RDMA kernel headers.
make[2]: Entering directory '/usr/src/kernels/5.14.0-362.8.1.el9_3.x86_64'
  CC [M]  /root/scst/scst/iscsi-scst/kernel/isert-scst/isert.o
<command-line>: fatal error: /usr/src/ofa_kernel/default/include/linux/compat-2.6.h: No such file or directory
compilation terminated.
make[3]: *** [scripts/Makefile.build:299: /root/scst/scst/iscsi-scst/kernel/isert-scst/isert.o] Error 1
make[2]: *** [Makefile:1928: /root/scst/scst/iscsi-scst/kernel/isert-scst] Error 2
make[2]: Leaving directory '/usr/src/kernels/5.14.0-362.8.1.el9_3.x86_64'
make[1]: *** [Makefile:143: mods] Error 2
make[1]: Leaving directory '/root/scst/scst/iscsi-scst'
make: *** [Makefile:238: iscsi] Error 2

**Comment by msdosx** [comment]
Confirmed on Rocky 8.9. the main problem is in the mellanox 23.10 driver

**Comment by lnocturno** [comment]
Hi,

I wasn't enable to reproduce the problem. I was using AlmaLinux 9.3 (kernel 5.14.0-362.13.1.el9_3.x86_64) and MOFED 23.10.1.1.9.
```
  Building against MOFED RDMA kernel headers.
make[3]: Entering directory '/usr/src/kernels/5.14.0-362.13.1.el9_3.x86_64'
  CC [M]  /usr/src/packages/BUILD/scst-3.8.0.7baf2866/iscsi-scst/kernel/isert-scst/isert.o
  CC [M]  /usr/src/packages/BUILD/scst-3.8.0.7baf2866/iscsi-scst/kernel/isert-scst/isert_login.o
  CC [M]  /usr/src/packages/BUILD/scst-3.8.0.7baf2866/iscsi-scst/kernel/isert-scst/iser_datamover.o
  CC [M]  /usr/src/packages/BUILD/scst-3.8.0.7baf2866/iscsi-scst/kernel/isert-scst/iser_rdma.o
  CC [M]  /usr/src/packages/BUILD/scst-3.8.0.7baf2866/iscsi-scst/kernel/isert-scst/iser_buf.o
  CC [M]  /usr/src/packages/BUILD/scst-3.8.0.7baf2866/iscsi-scst/kernel/isert-scst/iser_pdu.o
  CC [M]  /usr/src/packages/BUILD/scst-3.8.0.7baf2866/iscsi-scst/kernel/isert-scst/iser_global.o
  LD [M]  /usr/src/packages/BUILD/scst-3.8.0.7baf2866/iscsi-scst/kernel/isert-scst/isert-scst.o
  MODPOST /usr/src/packages/BUILD/scst-3.8.0.7baf2866/iscsi-scst/kernel/isert-scst/Module.symvers
  CC [M]  /usr/src/packages/BUILD/scst-3.8.0.7baf2866/iscsi-scst/kernel/isert-scst/isert-scst.mod.o
  LD [M]  /usr/src/packages/BUILD/scst-3.8.0.7baf2866/iscsi-scst/kernel/isert-scst/isert-scst.ko
  BTF [M] /usr/src/packages/BUILD/scst-3.8.0.7baf2866/iscsi-scst/kernel/isert-scst/isert-scst.ko
Skipping BTF generation for /usr/src/packages/BUILD/scst-3.8.0.7baf2866/iscsi-scst/kernel/isert-scst/isert-scst.ko due to unavailability of vmlinux
make[3]: Leaving directory '/usr/src/kernels/5.14.0-362.13.1.el9_3.x86_64'
make[2]: Leaving directory '/usr/src/packages/BUILD/scst-3.8.0.7baf2866/iscsi-scst'
```

Thanks,
Gleb
