### ISSUE TITLE
Issue with Kernel 5.15.0-97-generic and latest scst. Using ESXi.

### ISSUE THREAD

**Issue by cryptz2k** [SCST-project/scst#224]
I upgraded ubuntu kernel today and recompiled scst. I might have been running the january version prior to upgrade. I am working on trying to revert a few versions of scst before i downgrade the kernel. Basically i am unable to see my storage in esxi. i see the following in dmesg. Kernel is 5.15.0-97-generic. i was using 5.15.0-94-generic before the upgrade.

***update***

reverting to the original 3.8 release resolved the issue. Kernel is still 5.15.0-97. It seems to have been a recent commit that caused this, I suspect it was the Feb16 updates as i believe i upgraded scst since Jan 30th.

[  737.246144] BUG: kernel NULL pointer dereference, address: 0000000000000000
[  737.247310] #PF: supervisor read access in kernel mode
[  737.248467] #PF: error_code(0x0000) - not-present page
[  737.249613] PGD 0 P4D 0
[  737.250761] Oops: 0000 [#8] SMP NOPTI
[  737.251892] CPU: 15 PID: 3111 Comm: ISER-PSC-Net5 Tainted: P      D    OE     5.15.0-97-generic #107-Ubuntu
[  737.253039] Hardware name: Dell Inc. PowerEdge R740xd/07X9K0, BIOS 2.20.1 09/13/2023
[  737.254164] RIP: 0010:vdisk_exec_sai_16+0x79/0x270 [scst_vdisk]
[  737.255288] Code: 2b 04 25 28 00 00 00 0f 85 0a 02 00 00 48 83 c4 30 31 c0 41 5c 41 5d 5d c3 cc cc cc cc 49 8b 74 24 68 48 8b 4e 28 48 8b 41 30 <48> 8b 38 48 85 ff 74 0b 48 8b 87 48 03 00 00 48 8b 78 50 48 8b 01
[  737.257551] RSP: 0018:ffffaa36264ffd40 EFLAGS: 00010246
[  737.258652] RAX: 0000000000000000 RBX: 0000000000000000 RCX: ffff9d3e36d82000
[  737.259741] RDX: ffff9d3e7c6d4df2 RSI: ffff9d1ed0640a80 RDI: ffff9d3e3a8a3080
[  737.260830] RBP: ffffaa36264ffd80 R08: ffff9d3e7c6d4d00 R09: 0000000000000000
[  737.261903] R10: 0000000000000000 R11: 0000000000000000 R12: ffff9d3e7c6d4d00
[  737.262945] R13: ffff9d1ed0640a80 R14: 0000000000000000 R15: ffffffffc0c43b40
[  737.263988] FS:  0000000000000000(0000) GS:ffff9d5dafbc0000(0000) knlGS:0000000000000000
[  737.265041] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  737.266074] CR2: 0000000000000000 CR3: 00000020856b4004 CR4: 00000000007706e0
[  737.267096] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[  737.268105] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[  737.269102] PKRU: 55555554
[  737.270091] Call Trace:
[  737.271075]  <TASK>
[  737.272047]  ? show_trace_log_lvl+0x1d6/0x2ea
[  737.273034]  ? show_trace_log_lvl+0x1d6/0x2ea
[  737.273999]  ? vdev_do_job+0x37/0xd0 [scst_vdisk]
[  737.274959]  ? show_regs.part.0+0x23/0x29
[  737.275906]  ? __die_body.cold+0x8/0xd
[  737.276853]  ? __die+0x2b/0x37
[  737.277795]  ? page_fault_oops+0x13b/0x170
[  737.278733]  ? isert_pdu_send+0x9b/0xc0 [isert_scst]
[  737.279661]  ? do_user_addr_fault+0x321/0x670
[  737.280575]  ? exc_page_fault+0x77/0x170
[  737.281481]  ? asm_exc_page_fault+0x27/0x30
[  737.282376]  ? vdisk_exec_sai_16+0x79/0x270 [scst_vdisk]
[  737.283263]  vdev_do_job+0x37/0xd0 [scst_vdisk]
[  737.284132]  fileio_exec+0x24/0x30 [scst_vdisk]
[  737.284974]  scst_do_real_exec+0x59/0x140 [scst]
[  737.285845]  ? _raw_spin_unlock_bh+0x1e/0x30
[  737.286640]  scst_exec_check_blocking+0xc7/0x230 [scst]
[  737.287470]  scst_process_active_cmd+0x273/0x1c30 [scst]
[  737.288288]  scst_cmd_thread+0x17d/0x550 [scst]
[  737.289087]  ? wait_woken+0x70/0x70
[  737.289819]  ? scst_cmd_done_local+0x90/0x90 [scst]
[  737.290575]  kthread+0x127/0x150
[  737.291263]  ? set_kthread_struct+0x50/0x50
[  737.291936]  ret_from_fork+0x1f/0x30
[  737.292591]  </TASK>
[  737.293226] Modules linked in: scst_vdisk(OE) isert_scst(OE) iscsi_scst(OE) scst(OE) dlm rdma_cm iw_cm ib_cm bonding intel_rapl_msr intel_rapl_common isst_if_common skx_edac nfit x86_pkg_temp_thermal intel_powerclamp coretemp ipmi_ssif nls_iso8859_1 zfs(PO) kvm_intel zunicode(PO) kvm zzstd(O) zlua(O) zavl(PO) icp(PO) zcommon(PO) rapl znvpair(PO) spl(O) dell_smbios dcdbas intel_cstate dell_wmi_descriptor wmi_bmof mei_me input_leds joydev mei ioatdma intel_pch_thermal acpi_ipmi ipmi_si ipmi_devintf ipmi_msghandler acpi_power_meter mac_hid sch_fq_codel dm_multipath scsi_dh_rdac scsi_dh_emc scsi_dh_alua binfmt_misc msr efi_pstore ip_tables x_tables autofs4 btrfs blake2b_generic zstd_compress raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq libcrc32c raid1 raid0 multipath linear mlx5_ib ib_uverbs ib_core mgag200 drm_kms_helper hid_generic syscopyarea sysfillrect sysimgblt mlx5_core fb_sys_fops crct10dif_pclmul uas crc32_pclmul usbhid mlxfw cec psample
[  737.293343]  ghash_clmulni_intel hid usb_storage aesni_intel ixgbe crypto_simd igb xfrm_algo tls cryptd rc_core ahci i2c_i801 nvme dca pci_hyperv_intf megaraid_sas xhci_pci nvme_core drm i2c_algo_bit lpc_ich mdio i2c_smbus libahci xhci_pci_renesas wmi
[  737.300617] CR2: 0000000000000000
[  737.301377] ---[ end trace acea122bec946806 ]---
[  737.315667] RIP: 0010:vdisk_exec_sai_16+0x79/0x270 [scst_vdisk]
[  737.316461] Code: 2b 04 25 28 00 00 00 0f 85 0a 02 00 00 48 83 c4 30 31 c0 41 5c 41 5d 5d c3 cc cc cc cc 49 8b 74 24 68 48 8b 4e 28 48 8b 41 30 <48> 8b 38 48 85 ff 74 0b 48 8b 87 48 03 00 00 48 8b 78 50 48 8b 01
[  737.318063] RSP: 0018:ffffaa36264efd40 EFLAGS: 00010246
[  737.318861] RAX: 0000000000000000 RBX: 0000000000000000 RCX: ffff9d3e36d82000
[  737.319663] RDX: ffff9d3e7c6d4b32 RSI: ffff9d1ed0640a80 RDI: ffff9d3e3a8a2780
[  737.320480] RBP: ffffaa36264efd80 R08: ffff9d3e7c6d4a40 R09: 0000000000000000
[  737.321294] R10: 0000000000000000 R11: 0000000000000000 R12: ffff9d3e7c6d4a40
[  737.322104] R13: ffff9d1ed0640a80 R14: 0000000000000000 R15: ffffffffc0c43b40
[  737.322919] FS:  0000000000000000(0000) GS:ffff9d5dafbc0000(0000) knlGS:0000000000000000
[  737.323753] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  737.324602] CR2: 0000000000000000 CR3: 00000020856b4004 CR4: 00000000007706e0
[  737.325455] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[  737.326308] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[  737.327157] PKRU: 55555554

**Comment by lnocturno** [comment]
Hi,

Could you retest with the latest master branch?
This commit https://github.com/SCST-project/scst/commit/bb784929448c588f87d6b674ef79b65378d8146a should help/

Thanks,
Gleb

**Comment by cryptz2k** [comment]
Hi Gleb,

I can confirm this resolved the issue, thank you

**Comment by cryptz2k** [comment]
Hi,


I know it was just released, but the nightly builds don't seem to suggest any testing or development has been done for kernel 6.8. I wanted to check here before trying to upgrade my server. I wasn't sure if there were any known issues. If you need a person to try I am happy to.
