### ISSUE TITLE
SCST 3.3 and higher slow speed on 10 gig

### ISSUE THREAD

**Issue by Shivani-76** [SCST-project/scst#31]
Hi,

I used SCST with alot of happyness. But since a few weeks i migrated my san to Ubuntu 20.04 and went from SCST 3.2 to 3.3. I found out that i cannot get more than 2 Gigbit/s out of even the IOPS are way lower than the 3.2 version was on ubuntu 16.04, even i tried the 3.5 version but the same speed persist. I looked the mailinglists for the same issue but could not find anything in relation to this issue. This why i post it here. 

I am running the san in a VMware environment. But i ruled out my switches and vmware by installing a seperate linux machine with the optics directly connected to the san and even that resulted in the same speeds as i am seeing over the switched network onwards to the vmware.

Is there any reason why i am seeing this issues. I tried virtually everything in tuning and kernel tuning. but the speed just wont get above 2 gigbit/s

Any suggestions would be really welcome as i am pulling my hair out on this problem for a week now..

**Comment by lnocturno** [comment]
Could you please provide SCST config? You can obtain it with the command `scstadmin --write_config /dev/stdout`

You can also recheck the issue with SCST 3.3+ and Ubuntu 16.04, just to make sure it's a regression in SCST 3.3 and not how SCST works with a newer kernel.

**Comment by Shivani-76** [comment]
Here is the output of the config

![image](https://user-images.githubusercontent.com/84938745/157904757-71131fa6-7e82-4ae2-a30a-6cc5324edbb6.png)


I have tested this issue with 3.3 and 3.5 ( as shown in config it is now 3.5 ) but the same problem persist.

**Comment by Shivani-76** [comment]
This config is running on Ubuntu 16.04 now by the way....

**Comment by lnocturno** [comment]
Did you set the nv_cache attribute manually?
For what purposes are you using the cpu_mask attribute for the iSCSI target?

**Comment by Shivani-76** [comment]
the nv_cache is come from the same setup which i had running before the upgrade. The cpy_mask is came out trial and error before i start posting here. Without it is make no difference.

**Comment by lnocturno** [comment]
So, as far as I understand you are observing a performance regression of the blockio handler since SCST 3.3+, regardless of Linux Kernel version.

What do you think about to find the commit, which leads to a regression between SCST 3.2 and 3.3, using git bisect?
I can help you by creating the branch with the bisect git history.
