### ISSUE TITLE
scst 3.6.x  / kernel 5.17.0

### ISSUE THREAD

**Issue by limbo127** [SCST-project/scst#33]
Hello, 
module of scst 3.6.x does not compile with the new stable 5.17.x(0) kernel branch, 
can you patch it ?
Regards, 
Nicolas Prochazka

**Comment by lnocturno** [comment]
I have ported scst 3.6.x branch to 5.17 kernel. Could you recheck the build?

**Comment by limbo127** [comment]
Hello,
it's working.
Thanks
Nicolas

Le jeu. 24 mars 2022 à 12:26, Gleb Chesnokov ***@***.***> a
écrit :
