### ISSUE TITLE
RHEL 8.5 with Secure Boot enabled issues

### ISSUE THREAD

**Issue by mikeyjoon** [SCST-project/scst#4]
My SCST service does not want to come up on an RHEL 8.5 when Secure Boot is turned on; even after I have gone to the UEFI menu and registered the keys using MOK menu per README instructions here: https://github.com/bvanassche/scst/blob/master/README.module-signing

I get the following error:
================
● mediator-scst.service
Loaded: loaded (/etc/systemd/system/mediator-scst.service; enabled; vendor preset: disabled)
Active: failed (Result: exit-code) since Wed 2021-12-08 10:26:33 EST; 1 day 22h ago
Process: 7320 ExecStart=/etc/init.d/scst start (code=exited, status=5)

Dec 08 10:26:33 scs000040681 systemd[1]: mediator-scst.service: Service RestartSec=100ms expired, scheduling restart.
Dec 08 10:26:33 scs000040681 systemd[1]: mediator-scst.service: Scheduled restart job, restart counter is at 5.
Dec 08 10:26:33 scs000040681 systemd[1]: Stopped mediator-scst.service.
Dec 08 10:26:33 scs000040681 systemd[1]: mediator-scst.service: Start request repeated too quickly.
Dec 08 10:26:33 scs000040681 systemd[1]: mediator-scst.service: Failed with result 'exit-code'.
Dec 08 10:26:33 scs000040681 systemd[1]: Failed to start mediator-scst.service.

My System's Info:
===========
cat /etc/redhat-release:                             Red Hat Enterprise Linux release 8.5 (Ootpa)
mokutil --sb-state:                                     SecureBoot enabled
modprobe scst && modprobe -r scst: 
                                                                   modprobe: FATAL: Module scst not found in directory /lib/modules/4.18.0-348.2.1.el8_5.x86_64

What am I doing wrong, or need to do more when Secure Boot is turned on?
Any help/hint is greatly appreciated.

**Comment by lnocturno** [comment]
Did you install it after build?

What is the output of the following commands?
- find /lib/modules/ -name "scst.ko"
- rpm -qa | grep scst

**Comment by mikeyjoon** [comment]
Yes, it was installed after building on the system and using the .der keys generated to register the module with the kernel; then, reboot and register it in UEFI's MOK menus. Here are the output of the commands asked:

[root@localhost default]# find /lib/modules/ -name "scst.ko"
/lib/modules/4.18.0-348.el8.x86_64/extra/scst.ko
[root@localhost default]#
[root@localhost default]# rpm -qa | grep scst
[root@localhost default]#

**Comment by lnocturno** [comment]
> /lib/modules/4.18.0-348.el8.x86_64/extra/scst.ko

The scst.ko module have been install for 4.18.0-348 kernel version.
And you booted from the updated kernel version 4.18.0-348.2.1.

**Comment by mikeyjoon** [comment]
Ummmm...

I have a script that updates any kernel modules before installing SCST and in that script I do not Reboot after the update. Is there a way to fix the problem now and/or reinstall SCST in the correct Kernel version? Maybe in an scst.conf file????

**Comment by mikeyjoon** [comment]
I had to sign the scst_vdisk module for the service to work! Here is the command I used to sign:

/usr/src/kernels/4.18.0-348.el8.x86_64/scripts/sign-file sha256 ./scst_module_key.priv ./scst_module_key.der /lib/modules/4.18.0-348.el8.x86_64/extra/dev_handlers/scst_vdisk.ko

Thanks for your help and pointers. :-) @lnocturno
