### ISSUE TITLE
blkdev_issue_flush updated on RHEL8.6(4.18.0-372.9.1.el8.x86_64)

### ISSUE THREAD

**Issue by ssmuch** [SCST-project/scst#45]
Hi Folks,

Recently we tried compiling the scst package(scst3.6 and trunk) on RHEL 8.6, but the compiling failed (kernel: 4.18.0-372.9.1.el8.x86_64). The failure due the parameters is defined blkdev_issue_flush ./include/linux/blkdev.h:

/root/scst/scst-3.6/scst/src/dev_handlers/scst_vdisk.c:489:9: error: too many arguments to function 'blkdev_issue_flush'
   res = blkdev_issue_flush(bdev, gfp_mask);
         ^~~~~~~~~~~~~~~~~~
In file included from ./include/linux/blk-cgroup.h:23,
                 from ./include/linux/writeback.h:15,
                 from /root/scst/scst-3.6/scst/src/dev_handlers/scst_vdisk.c:40:
./include/linux/blkdev.h:1288:5: note: declared here
 int blkdev_issue_flush(struct block_device *bdev);
     ^~~~~~~~~~~~~~~~~~
make[3]: *** [scripts/Makefile.build:322: /root/scst/scst-3.6/scst/src/dev_handlers/scst_vdisk.o] Error 1
make[2]: *** [Makefile:1577: _module_/root/scst/scst-3.6/scst/src/dev_handlers] Error 2
make[2]: Leaving directory '/usr/src/kernels/4.18.0-372.9.1.el8.x86_64'
make[1]: *** [Makefile:76: all] Error 2
make[1]: Leaving directory '/root/scst/scst-3.6/scst/src'
make: *** [Makefile:36: all] Error 2
[root@net156-h105 scst]# uname -r
4.18.0-372.9.1.el8.x86_64
[root@net156-h105 scst]# cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.6 (Ootpa)
[root@net156-h105 scst]# pwd  
/root/scst/scst-3.6/scst

After updated the scst_vdisk.c with following changes, the compiling passed successfully.
[root@net156-h105 scst]# diff /root/scst/scst-3.6/scst/src/dev_handlers/scst_vdisk.c /root/scst/scst-3.6/scst/src/dev_handlers/scst_vdisk.c.orig 
488,490c488
< #elif LINUX_VERSION_CODE < KERNEL_VERSION(5, 12, 0) && \
<         (!defined(RHEL_MAJOR) || RHEL_MAJOR -0 < 8 ||   \
<          RHEL_MAJOR -0 == 8 && RHEL_MINOR -0 < 6)
---
> #elif LINUX_VERSION_CODE < KERNEL_VERSION(5, 12, 0)
[root@net156-h105 scst]# 

Could you help to review if the change is ok?

Thanks,
Kyle

**Comment by lnocturno** [comment]
Hi Kyle,

The patch is fine. It was applied to the master branch.
Thank you for the patch!

Thanks.
Gleb.

**Comment by ssmuch** [comment]
Hi Gleb,

Will the fix be uploaded the following address: 
https://github.com/SCST-project/scst/releases/tag/v3.6

Could you also help to update OS support on the release note(Add 8.6), please?

Thanks,
Kyle

**Comment by lnocturno** [comment]
I have ported the patch to the stable SCST 3.6 branch - https://github.com/SCST-project/scst/tree/3.6.x

**Comment by ssmuch** [comment]
Thanks Gleb, are there any known issues for scst 3.6 to support RHEL8?

Thanks,
Kyle

**Comment by lnocturno** [comment]
> Thanks Gleb, are there any known issues for scst 3.6 to support RHEL8?

AFAIK, there is no other issues for scst 3.6 to support RHEL8.

Thanks,
Gleb.

**Comment by ssmuch** [comment]
Thanks Gleb for the confirmation.
