### ISSUE TITLE
scst branch 3.6 vs 5.18.x

### ISSUE THREAD

**Issue by limbo127** [SCST-project/scst#53]
Hello,
module of scst 3.6.x does not compile with the new stable 5.18.x(0) kernel branch,
can you patch it ?
Regards,
Nicolas Prochazka

**Comment by lnocturno** [comment]
Hi,

Why don't you just use the master branch if you are using latest version of kernel?
I think if I port the 3.6.x stable branch every time a new kernel version is released, I may add the regression to the stable branch, what is not good.

Thanks,
Gleb.

**Comment by limbo127** [comment]
Hello,
We are using a fileio program which is difficult to readapt sometime to a
new branch 3.7
The stable branch is 3.6 so we keep it.
But your right, I understand that's is difficult and time consuming to
backport

Regards
Nicolas

Le jeu. 16 juin 2022 à 19:28, Gleb Chesnokov ***@***.***> a
écrit :

**Comment by lnocturno** [comment]
Hi,

What do you think if I create a new branch from 3.6.x that will be ported to new kernel versions especially for you?
Thus, the original 3.6.x stable branch will not be modified for other clients.

Thanks,
Gleb.
