### ISSUE TITLE
 weird action in alua when entering in transitioning mode

### ISSUE THREAD

**Issue by pucira** [SCST-project/scst#55]
Hi
I have just tested SCST 3.6 release and find out one weird  problem when using lvm in blockio device.
I created a lv and used it as block device. then I created a device group and added all targets and devices in it. after that changed the device group into transitioning, but device not closed or inactived in scst. but when device existed in any target it closed.
long story short, in version 3.5, after going into transitioning all devices at that device group is closed. but in version 3.6 if a device not in any target, device is not closed.
Is this behavior not a problem?

**Comment by lnocturno** [comment]
Hi,

Sorry for the long response and thank you for the report.
Could you provide your SCST config file. You can obtain it via `scstadmin --write_config config`

Thanks,
Gleb.

**Comment by lnocturno** [comment]
Hi,

It seems I have found a commit which makes this changes.

https://github.com/SCST-project/scst/commit/d333ce8232a496947be93bf3b01eb9d98c04bacd

But it was done in the context of version 3.5. Anyway, do you have any problems with these changes?

Thanks,
Gleb.

**Comment by lnocturno** [comment]
Hi,

Fix candidate was merged to the master branch. Tell me if you need this patch to be ported to the SCST 3.6 stable branch.
If you reproduce this problem again, feel free to reopen the issue.

Thanks,
Gleb.
