### ISSUE TITLE
Unable to compile ISCSI module on 5.15 kernel with ISER

### ISSUE THREAD

**Issue by msdosx** [SCST-project/scst#73]
Hello,
I have server on Ubuntu 20.04. The system uses HWE kernel 5.15
The server has few mellanox-6 network cards with MOFED 5.6 drivers

When I try to build iscsi module it always failed with infiband errors
Could you fix that?
Thank you.

:~/scst/scst# make iscsi
cd iscsi-scst && make all
make[1]: Entering directory '/root/scst/scst/iscsi-scst'
OFED_VERS = 5.6-OFED.5.6.2.0.9.1.kver.5.15.0-41-generic
make -C usr
make[2]: Entering directory '/root/scst/scst/iscsi-scst/usr'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/scst/scst/iscsi-scst/usr'
make -C /lib/modules/5.15.0-41-generic/build M=/root/scst/scst/iscsi-scst/kernel CONFTEST_CFLAGS="-DBAD_WR_MODIFIER= -DCM_HANDLER_EVENT_MODIFIER=               -DRDMA_CREATE_ID_TAKES_NET_ARG=0 -DRDMA_REJECT_HAS_FOUR_ARGS=0  -DSOCK_RECVMSG_HAS_FOUR_ARGS=0"\
        \
  modules
make[2]: Entering directory '/usr/src/linux-headers-5.15.0-41-generic'
  MODPOST /root/scst/scst/iscsi-scst/kernel/Module.symvers
  CC [M]  /root/scst/scst/iscsi-scst/kernel/iscsi-scst.mod.o
  LD [M]  /root/scst/scst/iscsi-scst/kernel/iscsi-scst.ko
  BTF [M] /root/scst/scst/iscsi-scst/kernel/iscsi-scst.ko
Skipping BTF generation for /root/scst/scst/iscsi-scst/kernel/iscsi-scst.ko due to unavailability of vmlinux
make[2]: Leaving directory '/usr/src/linux-headers-5.15.0-41-generic'
echo "mods:  INFINIBAND_ENABLED = true"
mods:  INFINIBAND_ENABLED = true
if true; then                                   \
  echo "  Building against MOFED RDMA kernel headers.";\
  make -C /lib/modules/5.15.0-41-generic/build M=/root/scst/scst/iscsi-scst/kernel/isert-scst ISER_CFLAGS="-I/usr/src/ofa_kernel/default/include -I/usr/src/ofa_kernel/default/include/uapi -include /usr/src/ofa_kernel/default/include/linux/compat-2.6.h -DMOFED_MAJOR=5 -DMOFED_MINOR=6-OFED -DOFED_FLAVOR=MOFED -DBAD_WR_MODIFIER= -DCM_HANDLER_EVENT_MODIFIER=               -DRDMA_CREATE_ID_TAKES_NET_ARG=0 -DRDMA_REJECT_HAS_FOUR_ARGS=0  -DSOCK_RECVMSG_HAS_FOUR_ARGS=0"   \
        \
  CONFIG_DTRACE= modules;                                       \
fi
  Building against MOFED RDMA kernel headers.
make[2]: Entering directory '/usr/src/linux-headers-5.15.0-41-generic'
  CC [M]  /root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.o
/root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c: In function ‘isert_post_recv’:
/root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c:90:50: error: passing argument 3 of ‘ib_post_recv’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   90 |  err = ib_post_recv(isert_conn->qp, first_ib_wr, &bad_wr);
      |                                                  ^~~~~~~
      |                                                  |
      |                                                  struct ib_recv_wr **
In file included from /usr/src/ofa_kernel/default/include/rdma/ib_mad.h:15,
                 from /usr/src/ofa_kernel/default/include/rdma/ib_cm.h:13,
                 from /root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c:44:
/usr/src/ofa_kernel/default/include/rdma/ib_verbs.h:3941:37: note: expected ‘const struct ib_recv_wr **’ but argument is of type ‘struct ib_recv_wr **’
 3941 |           const struct ib_recv_wr **bad_recv_wr)
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c: In function ‘isert_post_send’:
/root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c:137:50: error: passing argument 3 of ‘ib_post_send’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  137 |  err = ib_post_send(isert_conn->qp, first_ib_wr, &bad_wr);
      |                                                  ^~~~~~~
      |                                                  |
      |                                                  struct ib_send_wr **
In file included from /usr/src/ofa_kernel/default/include/rdma/ib_mad.h:15,
                 from /usr/src/ofa_kernel/default/include/rdma/ib_cm.h:13,
                 from /root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c:44:
/usr/src/ofa_kernel/default/include/rdma/ib_verbs.h:3924:37: note: expected ‘const struct ib_send_wr **’ but argument is of type ‘struct ib_send_wr **’
 3924 |           const struct ib_send_wr **bad_send_wr)
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c: In function ‘isert_post_drain_sq’:
/root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c:167:33: error: passing argument 3 of ‘ib_post_send’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  167 |       &drain_wr_sq->send_wr.wr, &bad_wr);
      |                                 ^~~~~~~
      |                                 |
      |                                 struct ib_send_wr **
In file included from /usr/src/ofa_kernel/default/include/rdma/ib_mad.h:15,
                 from /usr/src/ofa_kernel/default/include/rdma/ib_cm.h:13,
                 from /root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c:44:
/usr/src/ofa_kernel/default/include/rdma/ib_verbs.h:3924:37: note: expected ‘const struct ib_send_wr **’ but argument is of type ‘struct ib_send_wr **’
 3924 |           const struct ib_send_wr **bad_send_wr)
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c: In function ‘isert_post_drain_rq’:
/root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c:192:30: error: passing argument 3 of ‘ib_post_recv’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  192 |       &drain_wr_rq->recv_wr, &bad_wr);
      |                              ^~~~~~~
      |                              |
      |                              struct ib_recv_wr **
In file included from /usr/src/ofa_kernel/default/include/rdma/ib_mad.h:15,
                 from /usr/src/ofa_kernel/default/include/rdma/ib_cm.h:13,
                 from /root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c:44:
/usr/src/ofa_kernel/default/include/rdma/ib_verbs.h:3941:37: note: expected ‘const struct ib_recv_wr **’ but argument is of type ‘struct ib_recv_wr **’
 3941 |           const struct ib_recv_wr **bad_recv_wr)
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c: In function ‘isert_device_create’:
/root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c:998:8: error: macro "ib_create_cq" passed 6 arguments, but takes just 5
  998 |       i); /* completion vector */
      |        ^
In file included from /usr/src/ofa_kernel/default/include/rdma/ib_mad.h:15,
                 from /usr/src/ofa_kernel/default/include/rdma/ib_cm.h:13,
                 from /root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c:44:
/usr/src/ofa_kernel/default/include/rdma/ib_verbs.h:4009: note: macro "ib_create_cq" defined here
 4009 | #define ib_create_cq(device, cmp_hndlr, evt_hndlr, cq_ctxt, cq_attr) \
      |
/root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c:993:8: error: ‘ib_create_cq’ undeclared (first use in this function); did you mean ‘ib_create_wq’?
  993 |   cq = ib_create_cq(ib_dev,
      |        ^~~~~~~~~~~~
      |        ib_create_wq
/root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c:993:8: note: each undeclared identifier is reported only once for each function it appears in
/root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c: In function ‘isert_conn_create’:
/root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c:1233:47: error: ‘struct ib_device_attr’ has no member named ‘max_sge’; did you mean ‘max_cqe’?
 1233 |  isert_conn->max_sge = isert_dev->device_attr.max_sge - 3;
      |                                               ^~~~~~~
      |                                               max_cqe
/root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c: In function ‘isert_cm_conn_req_handler’:
/root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c:1482:2: error: too few arguments to function ‘rdma_reject’
 1482 |  rdma_reject(cm_id, NULL, 0
      |  ^~~~~~~~~~~
In file included from /usr/src/ofa_kernel/default/include/rdma/ib_cm.h:15,
                 from /root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c:44:
/usr/src/ofa_kernel/default/include/rdma/rdma_cm.h:272:5: note: declared here
  272 | int rdma_reject(struct rdma_cm_id *id, const void *private_data,
      |     ^~~~~~~~~~~
/root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c: In function ‘isert_setup_id’:
/root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c:1731:20: error: macro "rdma_create_id" requires 5 arguments, but only 4 given
 1731 |           IB_QPT_RC);
      |                    ^
In file included from /usr/src/ofa_kernel/default/include/rdma/ib_cm.h:15,
                 from /root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c:44:
/usr/src/ofa_kernel/default/include/rdma/rdma_cm.h:139: note: macro "rdma_create_id" defined here
  139 | #define rdma_create_id(net, event_handler, context, ps, qp_type)               \
      |
/root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c:1730:7: error: ‘rdma_create_id’ undeclared (first use in this function); did you mean ‘rdma_create_qp’?
 1730 |  id = rdma_create_id(isert_cm_evt_handler, portal, RDMA_PS_TCP,
      |       ^~~~~~~~~~~~~~
      |       rdma_create_qp
At top level:
/root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c:1617:12: warning: ‘isert_cm_evt_handler’ defined but not used [-Wunused-function]
 1617 | static int isert_cm_evt_handler(struct rdma_cm_id *cm_id,
      |            ^~~~~~~~~~~~~~~~~~~~
/root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.c:770:13: warning: ‘isert_cq_comp_handler’ defined but not used [-Wunused-function]
  770 | static void isert_cq_comp_handler(struct ib_cq *cq, void *context)
      |             ^~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:285: /root/scst/scst/iscsi-scst/kernel/isert-scst/iser_rdma.o] Error 1
make[2]: *** [Makefile:1875: /root/scst/scst/iscsi-scst/kernel/isert-scst] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-5.15.0-41-generic'
make[1]: *** [Makefile:141: mods] Error 2
make[1]: Leaving directory '/root/scst/scst/iscsi-scst'
make: *** [Makefile:226: iscsi] Error 2

**Comment by lnocturno** [comment]
Hi,

Thank you for the report. I will take a look at it soon.

Thanks,
Gleb

**Comment by lnocturno** [comment]
Are these the full build logs? It's strange, because I don't see the conftest building there.

What version of the SCST are you using?

**Comment by msdosx** [comment]
Hello Gleb,
It's only log from make iscsi command. There isn't any other output from the command.
I'm using the latest version from master.

**Comment by msdosx** [comment]
Hello Gleb,
Are there any news about the problem?
Thank you.

**Comment by lnocturno** [comment]
Hi,

I wasn't able to reproduce the problem on my setup (Ubuntu + MOFED 5.6). And I'm a little busy at the moment, so I will come back to this problem again on the next week.

Thanks,
Gleb.

**Comment by msdosx** [comment]
Hello Gleb,
I confirm that the latest 5.15 kernel fixed the problem.
Thank you.

**Comment by lnocturno** [comment]
Hi,

It's great.

Thanks,
Gleb

**Comment by msdosx** [comment]
Hello Gleb,
It's only log from make iscsi command. There isn't any other output from
the command.
I'm using the latest version from master.

пт, 29 июл. 2022 г., 19:24 Gleb Chesnokov ***@***.***>:
