### ISSUE TITLE
Typo in SCSTTarget RA breaks resource monitoring

### ISSUE THREAD

**Issue by alexcrow1974** [SCST-project/scst#80]
Line 126 has:

`<action name="status "      timeout="10" interval="10" depth="0" />`

Notice the extraneous space in "status ". This had me banging my head against the wall for a few hours today.

**Comment by lnocturno** [comment]
Hi,

Thank you for the detailed report and the root-cause analysis.

I have created a pull request to fix this problem. Could you take a look at it?

Thanks,
Gleb

**Comment by alexcrow1974** [comment]
I'm very sorry I didn't get back to you, but if this is now closed I've very grateful, just about to do a new deployment!
